### ISSUE TITLE
Player can't open or create sheets after joining

### ISSUE THREAD

**Issue by Pantus** [Rangertheman/motw-for-pbta#5]
When a joined player want's to open a sheet, or create a new actor I get this error.

I'll try to debug it myself when I'll have the time, but you seem to be quick with the responses.

```
foundry.js:747 TypeError: An error occurred while rendering PbtaActorSheet 44. Cannot read properties of undefined (reading 'character')
[Detected 1 package: system:pbta]
    at PbtaActorSheet._prepareCharacterItems (actor-sheet.js:258:54)
    at PbtaActorSheet.getData (actor-sheet.js:87:16)
    at PbtaActorSheet._render (foundry.js:5108:29)
    at PbtaActorSheet._render (foundry.js:5822:17)
    at PbtaActorSheet.render (foundry.js:5067:10)
    at PbtaActorSheet.render (foundry.js:6394:18)
    at ActorDirectory._onClickDocumentName (foundry.js:60848:16)
    at HTMLOListElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by Rangertheman** [comment]
I'll investigate the issue :)

May I ask what version of the PbtA system you're using?

**Comment by Pantus** [comment]
Thanks, sorry for not including it in the first place. 
PbtA version 0.7.1
motw-for-pbta version 0.1.3

**Comment by Pantus** [comment]
Seems like actorTypes array is undefined for the sheet.

**Comment by Pantus** [comment]
Latest PbtA system release has this line.
"Fixed an issue where TOML sheet configurations provided by modules wouldn't apply successfully for non-GM users."

Since your module uses actorTypes seemingly correctly, I'm pretty sure it's PbtA's fault. In case you agree, feel free to close this issue.

**Comment by Rangertheman** [comment]
I agree with your assessment. It's most likely a system issue. I have asked asacolips to have a look at it.
